name: take_notes
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.3+1
  image_picker: ^0.6.0+17

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.11.1+8
  cloud_firestore: ^0.12.7
  firebase_core: ^0.4.0+6
  get_it: ^1.0.3+2
  provider: ^3.0.0+1
  google_sign_in: ^4.0.4
  font_awesome_flutter: ^8.4.0
  flutter_statusbarcolor: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true